// AUTO-GENERATED by scripts/import-popurri.mjs — no editar a mano.
import kaptoceliaco from "./recipes/apto-celiaco.json?url";
import karrocesypastas from "./recipes/arroces-y-pastas.json?url";
import kbebidas from "./recipes/bebidas.json?url";
import kcarne from "./recipes/carne.json?url";
import kcelebraciones from "./recipes/celebraciones.json?url";
import kcumpleanos from "./recipes/cumpleanos.json?url";
import keconomicas from "./recipes/economicas.json?url";
import kensaladas from "./recipes/ensaladas.json?url";
import kfiestas from "./recipes/fiestas.json?url";
import kfrituras from "./recipes/frituras.json?url";
import kguisosysopas from "./recipes/guisos-y-sopas.json?url";
import khamburguesas from "./recipes/hamburguesas.json?url";
import khelados from "./recipes/helados.json?url";
import kinternacionales from "./recipes/internacionales.json?url";
import kmasassaladas from "./recipes/masas-saladas.json?url";
import kmermeladas from "./recipes/mermeladas.json?url";
import knavidad from "./recipes/navidad.json?url";
import kpanes from "./recipes/panes.json?url";
import kpascuas from "./recipes/pascuas.json?url";
import kpasteleria from "./recipes/pasteleria.json?url";
import kpescadosymariscos from "./recipes/pescados-y-mariscos.json?url";
import kpizzas from "./recipes/pizzas.json?url";
import kpollo from "./recipes/pollo.json?url";
import kpostres from "./recipes/postres.json?url";
import ksalsasydips from "./recipes/salsas-y-dips.json?url";
import ksaludables from "./recipes/saludables.json?url";
import ksincategoria from "./recipes/sin-categoria.json?url";
import ksnacks from "./recipes/snacks.json?url";
import kvegano from "./recipes/vegano.json?url";
import kvegetariano from "./recipes/vegetariano.json?url";

export interface PopurriCategory {
  id: string;
  name: string;
  count: number;
  url: string;
}

export const POPURRI_CATEGORIES: PopurriCategory[] = [
  { id: "apto-celiaco", name: "Apto Celiaco", count: 63, url: kaptoceliaco },
  { id: "arroces-y-pastas", name: "Arroces Y Pastas", count: 782, url: karrocesypastas },
  { id: "bebidas", name: "Bebidas", count: 139, url: kbebidas },
  { id: "carne", name: "Carne", count: 2609, url: kcarne },
  { id: "celebraciones", name: "Celebraciones", count: 19, url: kcelebraciones },
  { id: "cumpleanos", name: "Cumpleanos", count: 9, url: kcumpleanos },
  { id: "economicas", name: "Economicas", count: 443, url: keconomicas },
  { id: "ensaladas", name: "Ensaladas", count: 41, url: kensaladas },
  { id: "fiestas", name: "Fiestas", count: 155, url: kfiestas },
  { id: "frituras", name: "Frituras", count: 228, url: kfrituras },
  { id: "guisos-y-sopas", name: "Guisos Y Sopas", count: 369, url: kguisosysopas },
  { id: "hamburguesas", name: "Hamburguesas", count: 76, url: khamburguesas },
  { id: "helados", name: "Helados", count: 46, url: khelados },
  { id: "internacionales", name: "Internacionales", count: 441, url: kinternacionales },
  { id: "masas-saladas", name: "Masas Saladas", count: 404, url: kmasassaladas },
  { id: "mermeladas", name: "Mermeladas", count: 17, url: kmermeladas },
  { id: "navidad", name: "Navidad", count: 77, url: knavidad },
  { id: "panes", name: "Panes", count: 331, url: kpanes },
  { id: "pascuas", name: "Pascuas", count: 15, url: kpascuas },
  { id: "pasteleria", name: "Pasteleria", count: 1602, url: kpasteleria },
  { id: "pescados-y-mariscos", name: "Pescados Y Mariscos", count: 485, url: kpescadosymariscos },
  { id: "pizzas", name: "Pizzas", count: 186, url: kpizzas },
  { id: "pollo", name: "Pollo", count: 441, url: kpollo },
  { id: "postres", name: "Postres", count: 1706, url: kpostres },
  { id: "salsas-y-dips", name: "Salsas Y Dips", count: 24, url: ksalsasydips },
  { id: "saludables", name: "Saludables", count: 276, url: ksaludables },
  { id: "sin-categoria", name: "Sin Categoria", count: 292, url: ksincategoria },
  { id: "snacks", name: "Snacks", count: 36, url: ksnacks },
  { id: "vegano", name: "Vegano", count: 21, url: kvegano },
  { id: "vegetariano", name: "Vegetariano", count: 432, url: kvegetariano },
];
