// scripts/import-popurri.mjs
// Importa el scraping de recetas de Cocineros Argentinos (del repo `chata`,
// ~/GITLAB/chata) a src/data/popurri/, limpio y listo para el sitio.
// Genera:
//   src/data/popurri/recipes/<categoria>.json  -> [{ i, title, url, text }]
//   src/data/popurri/index.json                -> [{ t, c, i }] (índice de títulos)
//   src/data/popurri/manifest.ts               -> imports ?url + metadatos
//
// Uso: node scripts/import-popurri.mjs
//      CHATA_ROOT=/otra/ruta node scripts/import-popurri.mjs

import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const CHATA_DATA =
  process.env.CHATA_ROOT ?? "/home/pablo/GITLAB/chata/src/data";
const OUT = join(ROOT, "src", "data", "popurri");

const PREFIX = "knowledge-recetas-";
const SUFFIX = ".json";

function titleCase(id) {
  return id
    .split("-")
    .map((w) => (w ? w.charAt(0).toUpperCase() + w.slice(1) : w))
    .join(" ");
}

function cleanEntry(raw, idx) {
  const lines = raw.text.split("\n").map((l) => l.replace(/\r$/, ""));
  let i = 0;
  while (i < lines.length && !lines[i].trim()) i++;
  const title = i < lines.length ? lines[i].trim() : "(sin título)";

  const body = lines.slice(i + 1); // sin la línea del título
  while (body.length && !body[body.length - 1].trim()) body.pop();
  while (body.length && /^Fuente:/i.test(body[body.length - 1].trim())) body.pop();

  return { i: idx, title, url: raw.url, text: body.join("\n").trim() };
}

const files = readdirSync(CHATA_DATA)
  .filter((f) => f.startsWith(PREFIX) && f.endsWith(SUFFIX))
  .sort();

mkdirSync(join(OUT, "recipes"), { recursive: true });

const categories = [];
const index = [];
let total = 0;

for (const file of files) {
  const id = file.slice(PREFIX.length, -SUFFIX.length);
  const raw = JSON.parse(readFileSync(join(CHATA_DATA, file), "utf-8"));
  const entries = raw.map(cleanEntry);
  const dataFile = join(OUT, "recipes", `${id}.json`);
  writeFileSync(dataFile, JSON.stringify(entries));
  categories.push({ id, name: titleCase(id), count: entries.length });
  for (const e of entries) index.push({ t: e.title, c: id, i: e.i });
  total += entries.length;
  console.log(`${id.padEnd(24)} ${String(entries.length).padStart(5)} recetas -> ${dataFile}`);
}

writeFileSync(join(OUT, "index.json"), JSON.stringify(index));

const imports = categories
  .map((c) => {
    const ident = "k" + c.id.replace(/[^a-zA-Z0-9_$]/g, "");
    return { ident, c };
  });

const manifest = `// AUTO-GENERATED by scripts/import-popurri.mjs — no editar a mano.
${imports
  .map(({ ident, c }) => `import ${ident} from "./recipes/${c.id}.json?url";`)
  .join("\n")}

export interface PopurriCategory {
  id: string;
  name: string;
  count: number;
  url: string;
}

export const POPURRI_CATEGORIES: PopurriCategory[] = [
${imports
  .map(({ ident, c }) => `  { id: "${c.id}", name: "${c.name}", count: ${c.count}, url: ${ident} },`)
  .join("\n")}
];
`;
writeFileSync(join(OUT, "manifest.ts"), manifest);

console.log(`\nTotal: ${total} recetas en ${categories.length} categorías -> ${OUT}`);